### ISSUE TITLE
Error on Connect

### ISSUE THREAD

**Issue by beimoe** [BIPES/SocketServerWebREPL#1]
Console Connect to a Raspberry Pi via WLAN gives me errors. What is the problem here?

BIPES Project - Bridge started
Now, access the Python Console from a Web Browser using a WebREPL client
For example: https://micropython.org/webrepl/#127.0.0.1:8266/
New connection
1
========>>>>>>>>> prompt = >>> 
except on decode
stdout send: exception while writing to socket: 'NoneType' object has no attribute 'sendall'
stdout send: exception while writing to socket: 'NoneType' object has no attribute 'sendall'
stdout send: exception while writing to socket: 'NoneType' object has no attribute 'sendall'
stdout send: exception while writing to socket: 'NoneType' object has no attribute 'sendall'

**Comment by rafaelaroca** [comment]
Hi beimoe! Thanks for testing and contacting us. Just tested and worked here. Could you please follow these steps and test again:

Clone the repo:
git clone https://github.com/rafaelaroca/SocketServerWebREPL.git

Run the server:
python socketserverWebREPL.py

Connect from the browser:
Option 1:
http://micropython.org/webrepl/#127.0.0.1:8266/

Option 2:
http://bipes.net.br/beta2/ui/
Click console
Then paste the address ws://127.0.0.1:8266/ ad click connect

Important, you must then press 's' to start the session.

Could you please test again with these steps? Please feel free to contact us to check if other error happens, or this one is not solved.

best regards
Rafael

![bipes-shell-server](https://user-images.githubusercontent.com/31751413/111912408-294b2100-8a48-11eb-8e88-94e5d1014a62.png)

**Comment by rafaelaroca** [comment]
Hello, this issue is solved.
